Repository To-be-the-best-CSE403/CSE403-To_be_the_best-back, pull requests merged in 2024-02, with the labels that each got.

#29 Add Mock API For Teambuilder
  backend/api/index.py
  backend/api/test_views.py
  backend/api/views.py
Labels: feature

#31 Fix API CORS Error with Flask
  backend/api/index.py
  backend/requirements.txt
Labels: bug

#43 Add API Teambuilder with Archetype
  backend/api/views.py
  backend/src/api/teambuilder/teambuilder_algo.py
  backend/src/api/teambuilder/teambuilder_api.py
  backend/src/api/teambuilder/teambuilder_bo.json
  backend/src/api/teambuilder/teambuilder_ho.json
Labels: feature

#46 Improve Getting Started Page
  backend/public/teambuilder.gif
  backend/src/app/dashboard/getting-started/getting-started.mdx
Labels: feature

#48 Add API Usage Rate
  backend/.gitignore
  backend/api/views.py
  backend/package-lock.json
  backend/package.json
  backend/requirements.txt
  backend/src/api/usage/usage100.json
  backend/src/api/usage/usage_api.py
  backend/src/app/api/common-movesets/common-movesets.mdx
  backend/src/app/api/common-movesets/page.tsx
  backend/src/app/api/usage-rate/page.tsx
  backend/src/app/api/usage-rate/usage-rate.mdx
  backend/src/app/dashboard/common-movesets/api/page.tsx
  backend/src/app/dashboard/common-movesets/page.tsx
  backend/src/app/dashboard/teambuilder/api/page.tsx
  backend/src/app/dashboard/teambuilder/archetype/page.tsx
  backend/src/app/dashboard/teambuilder/page.tsx
  backend/src/app/dashboard/usage-rate/api/page.tsx
  backend/src/app/dashboard/usage-rate/page.tsx
  backend/src/components/Chart/UsageRateChart.tsx
  backend/src/config/index.ts
  backend/src/data/query.py
  backend/tests/test_basic_query.py
Labels: feature

#51 Add Usage Rate Data From Database
  backend/api/views.py
  backend/src/api/usage/usage100.json
  backend/src/api/usage/usage_api.py
  backend/src/data/constants.py
  backend/src/data/query_db.py
  backend/src/data/query_json.py
  backend/src/data/usage/2023-01_gen9ou-1500.json
  backend/src/data/usage/2023-02_gen9ou-1500.json
  backend/src/data/usage/2023-03_gen9ou-1500.json
  backend/src/data/usage/2023-04_gen9ou-1500.json
  backend/src/data/usage/2023-05_gen9ou-1500.json
  backend/src/data/usage/2023-06_gen9ou-1500.json
  backend/src/data/usage/2023-07_gen9ou-1500.json
  backend/src/data/usage/2023-08_gen9ou-1500.json
  backend/src/data/usage/2023-09_gen9ou-1500.json
  backend/src/data/usage/2023-10_gen9ou-1500.json
  backend/src/data/usage/2023-11_gen9ou-1500.json
  backend/src/data/usage/2023-12_gen9ou-1500.json
  backend/src/data/usage/2024-01_gen9ou-1500.json
  database/usage_parser.py
Labels: feature

#59 Add Demo Usage Rate Chart
  .github/workflows/preview.yml
  .github/workflows/production.yml
  backend/package.json
  backend/public/usage-rate.png
  backend/src/app/dashboard/usage-rate/page.tsx
  backend/src/components/Chart/UsageRateChart.tsx
Labels: feature

#60 Fix Vercel Serverless Functions Size Bug
  .github/workflows/preview.yml
  .github/workflows/production.yml
  .gitignore
  README.md
  backend/.vercelignore
  backend/api/check_effectiveness.py
  backend/api/index.py
  backend/api/test_views.py
  backend/api/views.py
  backend/package.json
  backend/public/favicon.ico
  backend/src/app/dashboard/archetype-team/archetype-team1.mdx
  backend/src/app/dashboard/archetype-team/archetype-team2.mdx
  backend/src/app/dashboard/archetype-team/page.tsx
  backend/src/app/dashboard/common-movesets/api/page.tsx
  backend/src/app/dashboard/teambuilder/api/page.tsx
  backend/src/app/dashboard/teambuilder/archetype/page.tsx
  backend/src/app/dashboard/usage-rate/api/page.tsx
  backend/src/app/dashboard/usage-rate/page.tsx
  backend/src/app/layout.tsx
  backend/src/components/Chart/UsageRateChart.tsx
  backend/src/data/query_json.py
  backend/vercel.json
  requirements.txt
Labels: bug

#53 Add API Usage Rate Timeline
  backend/api/index.py
  backend/api/test_views.py
  backend/api/views.py
  backend/public/usage-rate.png
  backend/src/components/Chart/UsageRateChart.tsx
  backend/src/data/usage/2023-01_gen9ou-1500.json
  backend/src/data/usage/2023-02_gen9ou-1500.json
  backend/src/data/usage/2023-03_gen9ou-1500.json
  backend/src/data/usage/2023-04_gen9ou-1500.json
  backend/src/data/usage/2023-05_gen9ou-1500.json
  backend/src/data/usage/2023-06_gen9ou-1500.json
  backend/src/data/usage/2023-07_gen9ou-1500.json
  backend/src/data/usage/2023-08_gen9ou-1500.json
  backend/src/data/usage/2023-09_gen9ou-1500.json
  backend/src/data/usage/2023-10_gen9ou-1500.json
  backend/src/data/usage/2023-11_gen9ou-1500.json
  backend/src/data/usage/2023-12_gen9ou-1500.json
  backend/src/data/usage/2024-01_gen9ou-1500.json
  backend/src/data/usage_parser.py
Labels: feature

#56 Add Top Usage Chart
  .github/workflows/preview.yml
  .github/workflows/production.yml
  backend/requirements.txt
Labels: feature

#62 Add API Usage Rate
  backend/api/views.py
  backend/src/data/constants.py
  backend/src/data/query_json.py
Labels: feature

#64 Fix pip requests missing
  backend/requirements.txt
Labels: bug

#66 Refactor API Usage Rate
  backend/api/views.py
  backend/src/api.ts
  backend/src/api/endpoints.py
  backend/src/app/dashboard/usage-rate/page.tsx
  backend/src/components/Chart/UsageTopChart.tsx
  backend/src/constants.py
  backend/src/data/query_json.py
  backend/src/data/query_smogon.py
Labels: feature

#68 Add Teambuilder Archetype and API Wiki
  README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app/dashboard/common-movesets/api/page.tsx
  backend/src/app/dashboard/teambuilder/api/page.tsx
  backend/src/app/dashboard/teambuilder/api/teambuilder-api.mdx
  backend/src/app/dashboard/teambuilder/archetype/page.tsx
  backend/src/app/dashboard/teambuilder/archetype/teambuilder-archetype.mdx
  backend/src/app/dashboard/teambuilder/page.tsx
  backend/src/app/dashboard/teambuilder/teambuilder.mdx
  backend/src/app/dashboard/usage-rate/api/page.tsx
  backend/src/app/layout.tsx
  backend/src/components/Mdx/Mdx.module.css
  backend/src/components/Wiki/ArchetypeEndpoint.tsx
  backend/src/config/index.ts
Labels: feature

#70 Add Usage Rate API Wiki
  backend/src/app/dashboard/usage-rate/api/page.tsx
  backend/src/app/dashboard/usage-rate/api/usage-rate-api.mdx
  backend/src/components/Wiki/UsageRateEndpoint.tsx
Labels: feature

#76 Add project importance
  backend/src/app/dashboard/about-pages/extension/about-the-extension-page.mdx
  backend/src/app/dashboard/about-pages/extension/page.tsx
  backend/src/app/dashboard/about-pages/pokemon-showdown/about-pokemon-showdown-page.mdx
  backend/src/app/dashboard/about-pages/pokemon-showdown/page.tsx
  backend/src/config/index.ts
Labels: documentation

#81 Add another bar graph and finished anime/movie section
  backend/public/statista-lifetime-gross-of-pokemon-franchise-us-and-canada-2023.png
  backend/src/app/dashboard/about-pages/pokemon-franchise/about-pokemon-franchise-page.mdx
Labels: documentation

#82 Add team archetype descriptions from Jason's finished file
  backend/src/app/dashboard/teambuilder/archetype/teambuilder-archetype.mdx
Labels: documentation
